services:
  fpm:
    extends:
      file: compose.services.yaml
      service: fpm
    depends_on:
      - mysql
    build:
      target: dev
    command: "php artisan serve --host 0.0.0.0"
    ports:
      - "${FPM_PORT:-8000}:8000"
  mysql:
    extends:
      file: compose.services.yaml
      service: mysql
    volumes:
      - ./docker/mysql/setup.sql:/docker-entrypoint-initdb.d/01.sql
  sonar:
    extends:
      service: sonar
      file: compose.services.yaml
