services:
  fpm:
    image: agilex-fpm/fpm:0.1.2
    build:
      context: .
      dockerfile: ./docker/fpm/Dockerfile
      target: base
    working_dir: /var/www/html
    volumes:
      - ./code:/var/www/html
  mysql:
    image: 'mysql:8.0'
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-password}"
      MYSQL_DATABASE: "${MYSQL_DATABASE:-laravel}"
      MYSQL_USER: "${MYSQL_USER:-user}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-password}"
    volumes:
      - ./data/mysql:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-ppassword" ]
      retries: 3
      timeout: 5s