openapi: 3.1.0
info:
  version: 0.1.0
  title: agilex
  description: Api test
  contact:
    name: Maurizio Urso
    email: izzius94@outlook.com
servers:
  - url: 'http://localhost:8000'
    description: Local
tags:
  - name: auth
  - name: orders
paths:
  /login:
    post:
      tags:
        - auth
      operationId: login
      description: Endpoint to log a user in
      requestBody:
        $ref: '#/components/requestBodies/login'
      responses:
        '200':
          description: OK
          $ref: '#/components/responses/login'
  /orders:
    get:
      operationId: orders-index
      tags:
        - orders
      security:
        - BearerAuth: []
      parameters:
        - schema:
            type: string
          in: query
          name: name
        - schema:
            type: string
          in: query
          name: description
        - schema:
            type: string
            format: date
          in: query
          name: date_start
        - schema:
            type: string
            format: date
          in: query
          name: date_end
        - schema:
            type: integer
            default: 1
            minimum: 1
          in: query
          name: page
      responses:
        '200':
          description: OK
          $ref: '#/components/responses/orders-list'
      description: Retrieve a user orders
    post:
      operationId: orders-store
      security:
        - BearerAuth: []
      description: create a new order
      tags:
        - orders
      requestBody:
        $ref: '#/components/requestBodies/create-order'
      responses:
        '200':
          description: OK
          $ref: '#/components/responses/order-created'
  '/orders/{id}':
    parameters:
      - $ref: '#/components/parameters/id'
    get:
      security:
        - BearerAuth: []
      tags:
        - orders
      summary: ''
      operationId: orders-get
      responses:
        '200':
          description: OK
          $ref: '#/components/responses/order'
      description: Get an order
    put:
      security:
        - BearerAuth: []
      description: Update an order
      tags:
        - orders
      summary: ''
      operationId: put-orders-id
      requestBody:
        $ref: '#/components/requestBodies/update-order'
      responses:
        '200':
          description: OK
          $ref: '#/components/responses/order-updated'
    delete:
      security:
        - BearerAuth: []
      description: Delete an order
      tags:
        - orders
      summary: ''
      operationId: delete-orders-id
      responses:
        '200':
          description: OK
          $ref: '#/components/responses/order-deleted'
components:
  requestBodies:
    create-order:
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
                x-stoplight:
                  id: 3lixm4v2vjep1
              description:
                type: string
                x-stoplight:
                  id: dus4b1cwmchiu
              products:
                type: array
                x-stoplight:
                  id: soxyf92ffwpbi
                items:
                  x-stoplight:
                    id: 5dkihao1gleu6
                  type: object
                  properties:
                    id:
                      type: integer
                      x-stoplight:
                        id: fu01406wqv978
                    quantity:
                      type: integer
                      x-stoplight:
                        id: r1j1e2y86y75d
      description: Body to create an order
    update-order:
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
                x-stoplight:
                  id: avj6hqyqxvwu4
              description:
                type: string
                x-stoplight:
                  id: pqt270fnd1hhx
              products:
                type: array
                x-stoplight:
                  id: 5cie32yvc2ier
                items:
                  x-stoplight:
                    id: 4ea0f7cxdoh65
                  type: object
                  properties:
                    id:
                      type: integer
                      x-stoplight:
                        id: xkw7us09fmas1
                    quantity:
                      type: integer
                      x-stoplight:
                        id: 1tyargkav67ec
    login:
      content:
        application/json:
          schema:
            type: object
            properties:
              email:
                type: string
                format: email
                max: 255
              password:
                type: string
                max: 255
            required:
              - email
              - password
  responses:
    order-created:
      description: Order created correctly
      content:
        application/json:
          schema:
            type: object
            properties:
              id:
                type: string
              shipped:
                type: boolean
              user_id:
                type: integer
              created_at:
                type: string
                format: date-time
                default: '2025-02-18T20:17:27.000000Z'
              updated_at:
                type: string
                format: date-time
    orders-list:
      description: List of orders
      content:
        application/json:
          schema:
            type: object
            properties:
              current_page:
                type: integer
                minimum: 1
              data:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    shipped:
                      type: boolean
                    user_id:
                      type: integer
                    created_at:
                      type: string
                      format: date-time
                      default: '2025-02-18T20:17:27.000000Z'
                    updated_at:
                      type: string
                      format: date-time
                    deleted_at:
                      type: string
                      format: date-time
                      default: '2025-02-18T20:17:27.000000Z'
              first_page_url:
                type: string
                x-stoplight:
                  id: zvfh3i0aqse5h
              from:
                type: integer
              next_page_url:
                type: string
              path:
                type: string
              per_page:
                type: integer
              prev_page_url:
                type: string
              to:
                type: integer
            required:
              - current_page
              - data
              - first_page_url
              - from
              - next_page_url
              - path
              - per_page
              - prev_page_url
              - to
    order:
      description: Order details
      content:
        application/json:
          schema:
            type: object
            properties:
              id:
                type: integer
                min: 1
              name:
                type: string
              description:
                type: string
              products:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    price:
                      tyoe: number
                    quantity:
                      type: integer
                    pivot:
                      type: object
                      properties:
                        order_id:
                          type: integer
                        product_id:
                          type: integer
                        quantity:
                          type: integer
    order-updated:
      description: Order updated
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                x-stoplight:
                  id: c5zw0gtg6w7jd
                default: Order updated.
    order-deleted:
      description: Order deleted
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                default: Order deleted.
    login:
      description: Login success
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                default: Logged in successfully.
              token:
                type: string
                default: 1|TM6NUp3ZYIF5h9cco2pIwVueutJOTWRTc0L6mwIpf00b4897
            required:
              - message
              - token
  parameters:
    id:
      name: id
      in: path
      required: true
      schema:
        type: integer
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer